// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b4f69619-ba80-4a9b-ad3d-bb95f9795548";

const char SSID[]               = "SSID";    // Network SSID (name)
const char PASS[]               = "networkpassword";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "secretdevicepassword";    // Secret device password

void onRedLedChange();

float humidity;
float pressure;
float temperature;
float temperature_esp32;
bool red_led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature_esp32, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
