// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "insertYourIDHere";

const char SSID[]               = "insertYourSSIDHere";    // Network SSID (name)
const char PASS[]               = "insertYourNetworkPasswordHere";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "InsertYourSecretDevicePasswordHere";    // Secret device password

void onRedLedChange();

float temperature_esp32;
bool red_led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature_esp32, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(red_led, READWRITE, ON_CHANGE, onRedLedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
